<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			

			<!-- Start Sign In Form -->
			<form action="/registrar" method="POST" class="fh5co-form animate-box" data-animate-effect="fadeIn">
				<h2>Inscreva-se</h2>
				
				<?php if($this->view->erroCadastro) { ?>
				<div>
					<small class="text text-danger">
						*Erro ao realizar cadastro! Verifique se os campos foram preenchidos corretamente.
					</small>
				</div>
				<?php } ?>

				<div class="form-group">
					<label for="name" class="sr-only">Nome</label>
					<input name="nome" type="text" value="<?=$this->view->usuario['nome']?>" class="form-control" id="name" placeholder="Nome" autocomplete="off">
				</div>
				<div class="form-group">
					<label for="email" class="sr-only">Email</label>
					<input name="email" type="email" value="<?=$this->view->usuario['email']?>" class="form-control" id="email" placeholder="Email" autocomplete="off">
				</div>
				<div class="form-group">
					<label for="password" class="sr-only">Senha</label>
					<input name="senha1" type="password" value="<?=$this->view->usuario['senha1']?>" class="form-control" id="password" placeholder="Senha" autocomplete="off">
				</div>
				<div class="form-group">
					<label for="re-password" class="sr-only">Confirme a senha</label>
					<input name="senha2" type="password" value="<?=$this->view->usuario['senha2']?>" class="form-control" id="re-password" placeholder="Confirme a senha" autocomplete="off">
				</div>

				<div class="form-group">
					<label for="remember"><input type="checkbox" id="remember">  Mantenha-me logado</label>
				</div>
				<div class="form-group">
					<p>Já possui uma conta? <a href="/">Entre agora</a></p>
				</div>
				<div class="form-group">
					<input type="submit" value="Inscrever-se" class="btn btn-primary">
				</div>
			</form>
			<!-- END Sign In Form -->

		</div>
	</div>
	<div class="row" style="padding-top: 60px; clear: both;">
		<div class="col-md-12 text-center" style="color:white;"><p><small>&copy; All Rights Reserved. Designed by <a href="https://freehtml5.co" target="_blank">FreeHTML5.co</a></small></p></div>
	</div>
</div>
	
	<!-- jQuery -->
	<script src="js/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="js/bootstrap.min.js"></script>
	<!-- Placeholder -->
	<script src="js/jquery.placeholder.min.js"></script>
	<!-- Waypoints -->
	<script src="js/jquery.waypoints.min.js"></script>
	<!-- Main JS -->
	<script src="js/main.js"></script>
